# Generated by Django 5.0.3 on 2024-03-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
